### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by nipafx** [nipafx/record-args#1]
Create an automated release process that publishes artifacts to Maven Central. Take the opportunity to take a closer look at [JReleaser](https://jreleaser.org/).

**Comment by nipafx** [comment]
Looks like Java 17 is enough for now. Downgrade to that and mention Java version in README. Speaking of README, include these fancy tags for main build and latest version at the top.

**Comment by aalmiray** [comment]
FWIW JReleaser does not (yet) publish artifacts to Maven Central, you'll have to use Maven for that. However, JReleaser can tag and create a Git release if you fancy that.

**Comment by nipafx** [comment]
Yes, I'd want that as well. Will give it a look when I get around to doing this boring release stuff. 😉

**Comment by nipafx** [comment]
In [a strategic master move](https://twitter.com/EsqTim/status/1547047570425380864), I did nothing for 2 years and now JReleaser supports releases to Maven Central. I've set everything up in acd2246, fa7f886, and f6871ba and it works swimmingly. Thanks @aalmiray for a great project! 🙌🏾
